connector.name=hive

hive.metastore.uri=thrift://hive-metastore:9083

# MinIO (S3A compatible)
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=admin
hive.s3.aws-secret-key=admin123
hive.s3.path-style-access=true

# REQUIRED in many setups
hive.s3.ssl.enabled=false

# Performance + correctness
hive.non-managed-table-writes-enabled=true
hive.storage-format=PARQUET